--- #YAML:1.0
name:               Time-HiRes
version:            1.9724
abstract:           High resolution alarm, sleep, gettimeofday, interval timers
author:
    - Jarkko Hietaniemi <jhi@iki.fi>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    Config:               0
    DynaLoader:           0
    Exporter:             0
    ExtUtils::MakeMaker:  0
    strict:               0
    Test::More:           0.82
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
